# Key-value pairs
title = "My Application"
version = "1.0"

# Tables (similar to sections or groups)
[database]
host = "localhost"
port = 3306
username = "user"
password = "password"

[server]
hostname = "example.com"
port = 8080

# Arrays of values
fruits = ["apple", "banana", "cherry"]

# Nested tables
[person]
name = "John"
age = 30
address = { street = "123 Main St", city = "Anytown" }
