# Define the package name and version
name = "example-package"
version = "1.0.0"

buildInputs = [
  "gcc"
  "make"
]# Define the build inputs

environment = {
  CC = "gcc";
}

meta = {
  description = "An example package in TOML format";
license = "MIT";
}
# Define environment variables
# Specify runtime dependencies
